# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9434327bbe35b25fb1755bb1aa8b194432c3a3d508c7b810d787a17be19c09b1ce35c3ee64eb4e9c413e02212a964050ca1f96dd8c99a1f7ce2cbba301d0e043

test:
  secret_key_base: 6276b8f0dc6a28fc4c5f928b3d05ecae01e87145c09d2d5bf06b81ca9870df3d47e73d09990f3f3e58816dcbc6f911c35437ab36306f3893d2425348a077f903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
